
# This is a basic workflow that is manually triggered

name: Delta9 run all tests 

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    ## Inputs the workflow accepts.
    inputs:
      test_target_env:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Environment [staging]'
        # Default value if no value is explicitly provided
        default: 'staging'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      tags:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Main Tags to run [@SANITY]'
        # Default value if no value is explicitly provided
        default: '@SANITY'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        # Install NPM dependencies, cache them correctly
        # and run all Cypress tests
        - name: install allure cli
          run: npm run allure:install
        - name: install allure plugin
          run: npm install -g allure-commandline --save-dev && npm i -D @shelex/cypress-allure-plugin
        - name: Cypress run with Cucumber
          uses: cypress-io/github-action@v4.2.0 # use the explicit version number
          with:
            command: npm run cypress:execution-allure -- --env ENVIRONMENT=${{ inputs.test_target_env }},allure=true,tags=${{ inputs.tags }}
        - name: Get Allure history
          uses: actions/checkout@v3
          if: always()
          continue-on-error: true
          with:
            ref: allure
            path: allure
        - name: Generate Allure Report
          uses: simple-elf/allure-report-action@master
          if: always()
          with:
            allure_results: allure-results
            gh_pages: allure
        - name: Deploy report to Github Pages
          if: always()
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: allure
            publish_dir: allure-history
              

#send-slack-notification:
 # #    needs: gen-allure-report
 #    needs: cypress-run
 #    #if: always()
 #    runs-on: ubuntu-latest
 #    steps:
 #      - name: Send notification to Slack workflow
 #        id: slack
 #        uses: slackapi/slack-github-action@v1.25.0
 #        if: always()
 #        with:
 #          # This data can be any valid JSON from a previous step in the GitHub Action
 #          payload: |
 #            {
 #              "projectName": "ACT LIMS",
 #              "executionStatus": "bar foo",
 #              "reportURL": "https://slingr-stack.github.io/cypress-act-lims/"
 #            }
 #        env:
 #            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
